# Generated by Django 5.2.8 on 2025-11-15 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'managers',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.location')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('coffee_option', models.BooleanField(default=False)),
                ('coffee_quantity', models.IntegerField(blank=True, null=True)),
                ('coffee_description', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.manager')),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.room')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
