# Generated by Django 4.2.7 on 2025-11-18 18:20

import api.models.booking
import api.models.location
import api.models.manager
import api.models.room
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.CharField(default=api.models.booking.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default=api.models.location.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.CharField(default=api.models.manager.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default=api.models.room.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
