# Generated by Django 4.2.7 on 2025-11-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_id_alter_location_id_alter_manager_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Reserva', max_length=200),
        ),
    ]
